import 'package:flutter/material.dart';

const List<String> filterList = ['House', 'Land', 'Office', 'Apartment'];

int currentFilterIndex = 0;
int currentDetailsIndex = 0;

const List<Map<String, dynamic>> propertyList = [
  {
    "image": "assets/png/house.png",
    "building_name": "Green Valley",
    "price": 8500000,
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "address": "45 Elm Street,",
    "rating": 4.5,
    "discount": "10%",
    "plots": 2,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Apartment",
    "bedroom": 3,
    "hall": 1,
    "kitchen": 1,
    "washroom": 2,
  },
  {
    "image": "assets/jpg/buiding.jpg",
    "building_name": "Sunshine Villas",
    "price": 14500000,
    "address": "Sunrise Road, Whitefield,",
    "rating": 4.8,
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "discount": "5%",
    "plots": 4,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Villa",
    "bedroom": 4,
    "hall": 2,
    "kitchen": 1,
    "washroom": 3,
  },
  {
    "image": "assets/jpg/building1.jpg",
    "building_name": "Hilltop Row Houses",
    "price": 6700000,
    "address": "32 Harmony Lane, ",
    "rating": 4.2,
    "discount": "8%",
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "plots": 1,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Row House",
    "bedroom": 2,
    "hall": 1,
    "kitchen": 1,
    "washroom": 1,
  },
  {
    "image": "assets/jpg/buiding2.jpg",
    "building_name": "Skyline Towers",
    "price": 9300000,
    "address": "Sector 62, Noida,",
    "rating": 4.4,
    "discount": "12%",
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "plots": 3,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Apartment",
    "bedroom": 3,
    "hall": 1,
    "kitchen": 1,
    "washroom": 2,
  },
  {
    "image": "assets/jpg/buiding3.jpg",
    "building_name": "Royal Duplex Homes",
    "price": 10500000,
    "address": "MG Road, Indore,",
    "rating": 4.6,
    "discount": "7%",
    "plots": 2,
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Duplex",
    "bedroom": 3,
    "hall": 2,
    "kitchen": 1,
    "washroom": 3,
  },
  {
    "image": "assets/jpg/buiding4.jpg",
    "building_name": "Orchid Heights",
    "price": 7200000,
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "address": "Salt Lake City, ",
    "rating": 4.3,
    "discount": "6%",
    "plots": 2,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Flat",
    "bedroom": 2,
    "hall": 1,
    "kitchen": 1,
    "washroom": 2,
  },
  {
    "image": "assets/jpg/buiding.jpg",
    "building_name": "Palm Grove Estate",
    "price": 16000000,
    "address": "ECR Road, Chennai",
    "rating": 4.9,
    "discount": "4%",
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "plots": 5,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Villa",
    "bedroom": 5,
    "hall": 2,
    "kitchen": 2,
    "washroom": 4,
  },
  {
    "image": "assets/jpg/building1.jpg",
    "building_name": "Maple Greens",
    "price": 8100000,
    "address": "Civil Lines, Jaipur,",
    "rating": 4.1,
    "discount": "9%",
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "plots": 2,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Independent House",
    "bedroom": 3,
    "hall": 1,
    "kitchen": 1,
    "washroom": 2,
  },
  {
    "image": "assets/jpg/buiding2.jpg",
    "building_name": "Elite Penthouse Suites",
    "price": 22000000,
    "address": "Bandra West, Mumbai",
    "rating": 5.0,
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "discount": "3%",
    "plots": 1,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Penthouse",
    "bedroom": 4,
    "hall": 2,
    "kitchen": 1,
    "washroom": 4,
  },
  {
    "image": "assets/jpg/buiding2.jpg",
    "building_name": "Countryside Farm Villas",
    "price": 12000000,
    "address": "Near Lavasa, Pune,",
    "rating": 4.7,
    "discount": "15%",
    'imageList': [
      "assets/jpg/buiding.jpg",
      "assets/jpg/building1.jpg",
      "assets/jpg/buiding2.jpg",
      "assets/jpg/buiding3.jpg",
      "assets/jpg/buiding4.jpg",
    ],
    "plots": 6,
    "description":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "types_of_house": "Farmhouse",
    "bedroom": 3,
    "hall": 1,
    "kitchen": 1,
    "washroom": 2,
  },
];
